version: '2'
services:
  expenses-mysql:
    extends:
      file: mysql.yml
      service: expenses-mysql
  expenses-app:
    image: expenses/expenses-app
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://expenses-mysql:3306/expenses?useSSL=false
    - EXPENSES_SLEEP=10 # gives time for the database to boot before the application
    ports:
    - 8181:8181
  expenses-nginx:
    image: expenses/expenses-nginx
    ports:
    - 8080:80